proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

applications:
- name: whisper_service
  route_prefix: /
  import_path: main:app
  runtime_env:
    working_dir: s3://ntoplabs-0001/main.zip
    pip:
      - torch
      - transformers
  deployments:
  - name: WhisperTranscriber
    num_replicas: 2
    ray_actor_options:
      num_cpus: 2
      num_gpus: 1
