proxy_location: EveryNode

http_options:
  host: 0.0.0.0
  port: 8000

applications:
- name: default
  route_prefix: /
  import_path: main:app
  runtime_env:
    working_dir: "s3://ntoplabs-0001/whisper_serve.zip"
    pip:
      - torch
      - transformers

  deployments:
  - name: WhisperTranscriber
    max_outgoing_requests: 1
    autoscaling_config:
      target_outgoing_requests: 25
      min_replicas: 8
      max_replicas: 60
    ray_actor_options:
      num_cpus: 1
      num_gpus: 0.25
  - name: WhisperAPI
    max_outgoing_requests: 1
    autoscaling_config:
      target_outgoing_requests: 25
      min_replicas: 8
      max_replicas: 40
    ray_actor_options:
      num_cpus: 1
